### ISSUE TITLE
Rendered notebooks have unclickable links and weird CSS

### ISSUE THREAD

**Issue by arvoelke** [arvoelke/nengolib#141]
Example (as of version 0.4.2): https://arvoelke.github.io/nengolib-docs/notebooks.examples.network.html

Console throws these errors on these pages:
```
notebooks.examples.rolling_window.html:11604 GET https://arvoelke.github.io/nengolib-docs/custom.css net::ERR_ABORTED
jquery.js:2 jQuery.Deferred exception: $.getQueryParameters is not a function TypeError: $.getQueryParameters is not a function
    at Object.highlightSearchWords (https://arvoelke.github.io/nengolib-docs/_static/doctools.js:193:20)
    at Object.init (https://arvoelke.github.io/nengolib-docs/_static/doctools.js:125:10)
    at HTMLDocument.<anonymous> (https://arvoelke.github.io/nengolib-docs/_static/doctools.js:286:17)
    at j (https://arvoelke.github.io/nengolib-docs/_static/jquery.js:2:29568)
    at k (https://arvoelke.github.io/nengolib-docs/_static/jquery.js:2:29882) undefined
r.Deferred.exceptionHook @ jquery.js:2
k @ jquery.js:2
setTimeout (async)
(anonymous) @ jquery.js:2
i @ jquery.js:2
fireWith @ jquery.js:2
fire @ jquery.js:2
i @ jquery.js:2
fireWith @ jquery.js:2
ready @ jquery.js:2
R @ jquery.js:2
jquery.js:2 Uncaught TypeError: $.getQueryParameters is not a function
    at Object.highlightSearchWords (doctools.js:193)
    at Object.init (doctools.js:125)
    at HTMLDocument.<anonymous> (doctools.js:286)
    at j (jquery.js:2)
    at k (jquery.js:2)
```

And not on any other pages.

**Comment by arvoelke** [comment]
Probably related: https://github.com/nengo/nengo/pull/1349
